spring.application.name=iot-core
# Configurações do Banco de Dados (Prontas para a Nuvem)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/iot_plataforma}
spring.datasource.username=${DB_USER:admin_iot}
spring.datasource.password=${DB_PASS:senha_nova_123}

# Configurações do RabbitMQ (Prontas para a Nuvem)
spring.rabbitmq.addresses=${RABBITMQ_URL:amqp://localhost:5672}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.security.token.secret=MinhaChaveSuperSecretaParaAIndustriaIot2026!