spring.application.name=iot-core
spring.datasource.url=jdbc:postgresql://postgres-db:5432/iot_plataforma
spring.datasource.username=admin_iot
spring.datasource.password=senha_nova_123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Configuração do RabbitMQ ---
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

api.security.token.secret=MinhaChaveSuperSecretaParaAIndustriaIot2026!